// config/regions.ts

export type CountryCode = "US" | "CA" | "UK" | "AU";

export type RegionId = string; // ISO 3166-2, t.ex. "US-TX"

export type Region = {
  id: RegionId;          // "US-TX"
  countryCode: CountryCode;
  slug: string;          // "texas"
  name: string;          // "Texas"
  displayName: string;   // "Texas" eller "Texas (United States)"
};

export const regions: Region[] = [
  {
    id: "US-TX",
    countryCode: "US",
    slug: "texas",
    name: "Texas",
    displayName: "Texas",
  },
  {
    id: "US-CA",
    countryCode: "US",
    slug: "california",
    name: "California",
    displayName: "California",
  },
  {
    id: "US-VA",
    countryCode: "US",
    slug: "virginia",
    name: "Virginia",
    displayName: "Virginia",
  },
  {
    id: "US-MI",
    countryCode: "US",
    slug: "michigan",
    name: "Michigan",
    displayName: "Michigan",
  },  
  { id: "US-MN", countryCode: "US", slug: "minnesota", name: "Minnesota", displayName: "Minnesota" },
  { id: "US-UT", countryCode: "US", slug: "utah", name: "Utah", displayName: "Utah" },
  { id: "US-AL", countryCode: "US", slug: "alabama", name: "Alabama", displayName: "Alabama" },
  { id: "US-OK", countryCode: "US", slug: "oklahoma", name: "Oklahoma", displayName: "Oklahoma" },
  { id: "US-HI", countryCode: "US", slug: "hawaii", name: "Hawaii", displayName: "Hawaii" },
  { id: "US-KS", countryCode: "US", slug: "kansas", name: "Kansas", displayName: "Kansas" },
  { id: "US-ID", countryCode: "US", slug: "idaho", name: "Idaho", displayName: "Idaho" },
  { id: "US-KY", countryCode: "US", slug: "kentucky", name: "Kentucky", displayName: "Kentucky" },
  { id: "US-IA", countryCode: "US", slug: "iowa", name: "Iowa", displayName: "Iowa" },
  { id: "US-ME", countryCode: "US", slug: "maine", name: "Maine", displayName: "Maine" },
  { id: "US-DE", countryCode: "US", slug: "delaware", name: "Delaware", displayName: "Delaware" },
  { id: "US-MS", countryCode: "US", slug: "mississippi", name: "Mississippi", displayName: "Mississippi" },
  { id: "US-OH", countryCode: "US", slug: "ohio", name: "Ohio", displayName: "Ohio" },
  { id: "US-AR", countryCode: "US", slug: "arkansas", name: "Arkansas", displayName: "Arkansas" },
  { id: "US-MT", countryCode: "US", slug: "montana", name: "Montana", displayName: "Montana" },
  { id: "US-NE", countryCode: "US", slug: "nebraska", name: "Nebraska", displayName: "Nebraska" },
  { id: "US-AZ", countryCode: "US", slug: "arizona", name: "Arizona", displayName: "Arizona" },
  { id: "US-CO", countryCode: "US", slug: "colorado", name: "Colorado", displayName: "Colorado" },
  { id: "US-CT", countryCode: "US", slug: "connecticut", name: "Connecticut", displayName: "Connecticut" },
  { id: "US-FL", countryCode: "US", slug: "florida", name: "Florida", displayName: "Florida" },
  { id: "US-GA", countryCode: "US", slug: "georgia", name: "Georgia", displayName: "Georgia" },
  { id: "US-IN", countryCode: "US", slug: "indiana", name: "Indiana", displayName: "Indiana" },
  { id: "US-LA", countryCode: "US", slug: "louisiana", name: "Louisiana", displayName: "Louisiana" },
  { id: "US-MD", countryCode: "US", slug: "maryland", name: "Maryland", displayName: "Maryland" },
  { id: "US-MA", countryCode: "US", slug: "massachusetts", name: "Massachusetts", displayName: "Massachusetts" },
  { id: "US-MO", countryCode: "US", slug: "missouri", name: "Missouri", displayName: "Missouri" },
  { id: "US-NV", countryCode: "US", slug: "nevada", name: "Nevada", displayName: "Nevada" },
  { id: "US-NJ", countryCode: "US", slug: "new-jersey", name: "New Jersey", displayName: "New Jersey" },
  { id: "US-NY", countryCode: "US", slug: "new-york", name: "New York", displayName: "New York" },
  { id: "US-NC", countryCode: "US", slug: "north-carolina", name: "North Carolina", displayName: "North Carolina" },
  { id: "US-OR", countryCode: "US", slug: "oregon", name: "Oregon", displayName: "Oregon" },
  { id: "US-PA", countryCode: "US", slug: "pennsylvania", name: "Pennsylvania", displayName: "Pennsylvania" },
  { id: "US-RI", countryCode: "US", slug: "rhode-island", name: "Rhode Island", displayName: "Rhode Island" },
  { id: "US-SC", countryCode: "US", slug: "south-carolina", name: "South Carolina", displayName: "South Carolina" },
  { id: "US-SD", countryCode: "US", slug: "south-dakota", name: "South Dakota", displayName: "South Dakota" },
  { id: "US-TN", countryCode: "US", slug: "tennessee", name: "Tennessee", displayName: "Tennessee" },
  { id: "US-WA", countryCode: "US", slug: "washington", name: "Washington", displayName: "Washington" },
  { id: "US-WI", countryCode: "US", slug: "wisconsin", name: "Wisconsin", displayName: "Wisconsin" },
  { id: "US-WY", countryCode: "US", slug: "wyoming", name: "Wyoming", displayName: "Wyoming" },
  { id: "US-PR", countryCode: "US", slug: "puerto-rico", name: "Puerto Rico", displayName: "Puerto Rico" },
  { id: "US-CA-ALAMEDA-COUNTY", countryCode: "US", slug: "alameda-county-california", name: "Alameda County", displayName: "Alameda County, California" },
  { id: "US-FL-BROWARD-COUNTY", countryCode: "US", slug: "broward-county-florida", name: "Broward County", displayName: "Broward County, Florida" },
  { id: "US-NV-CLARK-COUNTY", countryCode: "US", slug: "clark-county-nevada", name: "Clark County", displayName: "Clark County, Nevada" },
  { id: "US-NY-ERIE-COUNTY", countryCode: "US", slug: "erie-county-new-york", name: "Erie County", displayName: "Erie County, New York" },
  { id: "US-OH-FRANKLIN-COUNTY", countryCode: "US", slug: "franklin-county-ohio", name: "Franklin County", displayName: "Franklin County, Ohio" },
  { id: "US-PA-FRANKLIN-COUNTY", countryCode: "US", slug: "franklin-county-pennsylvania", name: "Franklin County", displayName: "Franklin County, Pennsylvania" },
  { id: "US-NY-FRANKLIN-COUNTY", countryCode: "US", slug: "franklin-county-new-york", name: "Franklin County", displayName: "Franklin County, New York" },
  { id: "US-TX-FRANKLIN-COUNTY", countryCode: "US", slug: "franklin-county-texas", name: "Franklin County", displayName: "Franklin County, Texas" },
  { id: "US-FL-POLK-COUNTY", countryCode: "US", slug: "polk-county-florida", name: "Polk County", displayName: "Polk County, Florida" },
  { id: "US-NY-SUFFOLK-COUNTY", countryCode: "US", slug: "suffolk-county-new-york", name: "Suffolk County", displayName: "Suffolk County, New York" },
  { id: "US-TX-AUSTIN-CITY", countryCode: "US", slug: "austin-city-texas", name: "Austin", displayName: "Austin" },
  { id: "US-MA-BOSTON-CITY", countryCode: "US", slug: "boston-city-massachusetts", name: "Boston", displayName: "Boston" },
  { id: "US-TX-DALLAS-CITY", countryCode: "US", slug: "dallas-texas", name: "Dallas", displayName: "Dallas" },
  { id: "US-TX-HOUSTON-CITY", countryCode: "US", slug: "houston-texas", name: "Houston", displayName: "Houston" },
  { id: "US-MN-MINNEAPOLIS-CITY", countryCode: "US", slug: "minneapolis", name: "Minneapolis", displayName: "Minneapolis" },
  { id: "US-NY-NEW-YORK-CITY", countryCode: "US", slug: "new-york-city-new-york", name: "New York City", displayName: "New York City" },
  { id: "US-CA-SAN-FRANCISCO-CITY", countryCode: "US", slug: "san-francisco-california", name: "San Francisco", displayName: "San Francisco" },
  { id: "US-CA-SAN-JOSE-CITY", countryCode: "US", slug: "san-jose-california", name: "San Jose", displayName: "San Jose" },
  { id: "US-UT-SALT-LAKE-CITY", countryCode: "US", slug: "salt-lake-city-utah", name: "Salt Lake City", displayName: "Salt Lake City" },
  { id: "US-DC", countryCode: "US", slug: "washington-dc", name: "Washington, District of Columbia", displayName: "Washington, District of Columbia" },
  { id: "US-VT", countryCode: "US", slug: "vermont", name: "Vermont", displayName: "Vermont" },
  { id: "US-NC-WAKE-COUNTY", countryCode: "US", slug: "wake-county-north-carolina", name: "Wake County", displayName: "Wake County" },
  { id: "US-NC-MECKLENBURG-COUNTY", countryCode: "US", slug: "mecklenburg-county-north-carolina", name: "Mecklenburg County", displayName: "Mecklenburg County" },
  { id: "US-AZ-PHOENIX-CITY", countryCode: "US", slug: "phoenix-arizona", name: "Phoenix", displayName: "Phoenix" },
  { id: "US-CO-DENVER-CITY", countryCode: "US", slug: "denver-colorado", name: "Denver", displayName: "Denver" },
  { id: "US-IL", countryCode: "US", slug: "illinois", name: "Illinois", displayName: "Illinois" },
  { id: "US-AK", countryCode: "US", slug: "alaska", name: "Alaska", displayName: "Alaska" },
  { id: "US-NM", countryCode: "US", slug: "new-mexico", name: "New Mexico", displayName: "New Mexico" },
  { id: "US-ND", countryCode: "US", slug: "north-dakota", name: "North Dakota", displayName: "North Dakota" },
  { id: "US-WV", countryCode: "US", slug: "west-virginia", name: "West Virginia", displayName: "West Virginia" },
  { id: "US-CO-COLORADO-SPRINGS-CITY", countryCode: "US", slug: "colorado-springs-city-colorado", name: "Colorado Springs", displayName: "Colorado Springs, Colorado" },  
  { id: "US-SC-AIKEN-COUNTY", countryCode: "US", slug: "aiken-county-south-carolina", name: "Aiken County", displayName: "Aiken County, South Carolina" },
  { id: "US-PA-ALLEGHENY-COUNTY", countryCode: "US", slug: "allegheny-county-pennsylvania", name: "Allegheny County", displayName: "Allegheny County, Pennsylvania" },
  { id: "US-IN-ALLEN-COUNTY", countryCode: "US", slug: "allen-county-indiana", name: "Allen County", displayName: "Allen County, Indiana" },
  { id: "US-SC-ANDERSON-COUNTY", countryCode: "US", slug: "anderson-county-south-carolina", name: "Anderson County", displayName: "Anderson County, South Carolina" },
  { id: "US-MD-ANNE-ARUNDEL-COUNTY", countryCode: "US", slug: "anne-arundel-county-maryland", name: "Anne Arundel County", displayName: "Anne Arundel County, Maryland" },
  { id: "US-MN-ANOKA-COUNTY", countryCode: "US", slug: "anoka-county-minnesota", name: "Anoka County", displayName: "Anoka County, Minnesota" },
  { id: "US-AL-BALDWIN-COUNTY", countryCode: "US", slug: "baldwin-county-alabama", name: "Baldwin County", displayName: "Baldwin County, Alabama" },
  { id: "US-MD-BALTIMORE-COUNTY", countryCode: "US", slug: "baltimore-county-maryland", name: "Baltimore County", displayName: "Baltimore County, Maryland" },
  { id: "US-TX-BELL-COUNTY", countryCode: "US", slug: "bell-county-texas", name: "Bell County", displayName: "Bell County, Texas" },
  { id: "US-SC-BERKELEY-COUNTY", countryCode: "US", slug: "berkeley-county-south-carolina", name: "Berkeley County", displayName: "Berkeley County, South Carolina" },
  { id: "US-NM-BERNALILLO-COUNTY", countryCode: "US", slug: "bernalillo-county-new-mexico", name: "Bernalillo County", displayName: "Bernalillo County, New Mexico" },
  { id: "US-CO-BOULDER-COUNTY", countryCode: "US", slug: "boulder-county-colorado", name: "Boulder County", displayName: "Boulder County, Colorado" },
  { id: "US-TX-BRAZORIA-COUNTY", countryCode: "US", slug: "brazoria-county-texas", name: "Brazoria County", displayName: "Brazoria County, Texas" },
  { id: "US-NC-BUNCOMBE-COUNTY", countryCode: "US", slug: "buncombe-county-north-carolina", name: "Buncombe County", displayName: "Buncombe County, North Carolina" },
  { id: "US-ND-BURLEIGH-COUNTY", countryCode: "US", slug: "burleigh-county-north-dakota", name: "Burleigh County", displayName: "Burleigh County, North Dakota" },
  { id: "US-MN-CARVER-COUNTY", countryCode: "US", slug: "carver-county-minnesota", name: "Carver County", displayName: "Carver County, Minnesota" },
  { id: "US-SC-CHARLESTON-COUNTY", countryCode: "US", slug: "charleston-county-south-carolina", name: "Charleston County", displayName: "Charleston County, South Carolina" },
  { id: "US-OR-CLACKAMAS-COUNTY", countryCode: "US", slug: "clackamas-county-oregon", name: "Clackamas County", displayName: "Clackamas County, Oregon" },
  { id: "US-FL-CLAY-COUNTY", countryCode: "US", slug: "clay-county-florida", name: "Clay County", displayName: "Clay County, Florida" },
  { id: "US-MN-CLAY-COUNTY", countryCode: "US", slug: "clay-county-minnesota", name: "Clay County", displayName: "Clay County, Minnesota" },
  { id: "US-MO-CLAY-COUNTY", countryCode: "US", slug: "clay-county-missouri", name: "Clay County", displayName: "Clay County, Missouri" },
  { id: "US-NC-CLAY-COUNTY", countryCode: "US", slug: "clay-county-north-carolina", name: "Clay County", displayName: "Clay County, North Carolina" },
  { id: "US-GA-COBB-COUNTY", countryCode: "US", slug: "cobb-county-georgia", name: "Cobb County", displayName: "Cobb County, Georgia" },
  { id: "US-FL-COLLIER-COUNTY", countryCode: "US", slug: "collier-county-florida", name: "Collier County", displayName: "Collier County, Florida" },
  { id: "US-TX-COLLIN-COUNTY", countryCode: "US", slug: "collin-county-texas", name: "Collin County", displayName: "Collin County, Texas" },
  { id: "US-TX-COMAL-COUNTY", countryCode: "US", slug: "comal-county-texas", name: "Comal County", displayName: "Comal County, Texas" },
  { id: "US-CA-CONTRA-COSTA-COUNTY", countryCode: "US", slug: "contra-costa-county-california", name: "Contra Costa County", displayName: "Contra Costa County, California" },
  { id: "US-IL-COOK-COUNTY", countryCode: "US", slug: "cook-county-illinois", name: "Cook County", displayName: "Cook County, Illinois" },
  { id: "US-OH-CUYAHOGA-COUNTY", countryCode: "US", slug: "cuyahoga-county-ohio", name: "Cuyahoga County", displayName: "Cuyahoga County, Ohio" },
  { id: "US-MN-DAKOTA-COUNTY", countryCode: "US", slug: "dakota-county-minnesota", name: "Dakota County", displayName: "Dakota County, Minnesota" },
  { id: "US-TX-DALLAS-COUNTY", countryCode: "US", slug: "dallas-county-texas", name: "Dallas County", displayName: "Dallas County, Texas" },
  { id: "US-WI-DANE-COUNTY", countryCode: "US", slug: "dane-county-wisconsin", name: "Dane County", displayName: "Dane County, Wisconsin" },
  { id: "US-UT-DAVIS-COUNTY", countryCode: "US", slug: "davis-county-utah", name: "Davis County", displayName: "Davis County, Utah" },
  { id: "US-TX-DENTON-COUNTY", countryCode: "US", slug: "denton-county-texas", name: "Denton County", displayName: "Denton County, Texas" },
  { id: "US-SC-DORCHESTER-COUNTY", countryCode: "US", slug: "dorchester-county-south-carolina", name: "Dorchester County", displayName: "Dorchester County, South Carolina" },
  { id: "US-CO-DOUGLAS-COUNTY", countryCode: "US", slug: "douglas-county-colorado", name: "Douglas County", displayName: "Douglas County, Colorado" },
  { id: "US-NE-DOUGLAS-COUNTY", countryCode: "US", slug: "douglas-county-nebraska", name: "Douglas County", displayName: "Douglas County, Nebraska" },
  { id: "US-OR-DOUGLAS-COUNTY", countryCode: "US", slug: "douglas-county-oregon", name: "Douglas County", displayName: "Douglas County, Oregon" },
  { id: "US-IL-DUPAGE-COUNTY", countryCode: "US", slug: "dupage-county-illinois", name: "DuPage County", displayName: "DuPage County, Illinois" },
  { id: "US-NC-DURHAM-COUNTY", countryCode: "US", slug: "durham-county-north-carolina", name: "Durham County", displayName: "Durham County, North Carolina" },
  { id: "US-CO-EL-PASO-COUNTY", countryCode: "US", slug: "el-paso-county-colorado", name: "El Paso County", displayName: "El Paso County, Colorado" },
  { id: "US-TX-EL-PASO-COUNTY", countryCode: "US", slug: "el-paso-county-texas", name: "El Paso County", displayName: "El Paso County, Texas" },
  { id: "US-TX-ELLIS-COUNTY", countryCode: "US", slug: "ellis-county-texas", name: "Ellis County", displayName: "Ellis County, Texas" },
  { id: "US-FL-ESCAMBIA-COUNTY", countryCode: "US", slug: "escambia-county-florida", name: "Escambia County", displayName: "Escambia County, Florida" },
  { id: "US-AL-ETOWAH-COUNTY", countryCode: "US", slug: "etowah-county-alabama", name: "Etowah County", displayName: "Etowah County, Alabama" },
  { id: "US-VA-FAIRFAX-COUNTY", countryCode: "US", slug: "fairfax-county-virginia", name: "Fairfax County", displayName: "Fairfax County, Virginia" },
  { id: "US-GA-FORSYTH-COUNTY", countryCode: "US", slug: "forsyth-county-georgia", name: "Forsyth County", displayName: "Forsyth County, Georgia" },
  { id: "US-MD-FREDERICK-COUNTY", countryCode: "US", slug: "frederick-county-maryland", name: "Frederick County", displayName: "Frederick County, Maryland" },
  { id: "US-CA-FRESNO-COUNTY", countryCode: "US", slug: "fresno-county-california", name: "Fresno County", displayName: "Fresno County, California" },
  { id: "US-TX-GALVESTON-COUNTY", countryCode: "US", slug: "galveston-county-texas", name: "Galveston County", displayName: "Galveston County, Texas" },
  { id: "US-NC-GASTON-COUNTY", countryCode: "US", slug: "gaston-county-north-carolina", name: "Gaston County", displayName: "Gaston County, North Carolina" },
  { id: "US-TX-GRAYSON-COUNTY", countryCode: "US", slug: "grayson-county-texas", name: "Grayson County", displayName: "Grayson County, Texas" },
  { id: "US-OH-GREENE-COUNTY", countryCode: "US", slug: "greene-county-ohio", name: "Greene County", displayName: "Greene County, Ohio" },
  { id: "US-SC-GREENVILLE-COUNTY", countryCode: "US", slug: "greenville-county-south-carolina", name: "Greenville County", displayName: "Greenville County, South Carolina" },
  { id: "US-NC-GUILFORD-COUNTY", countryCode: "US", slug: "guilford-county-north-carolina", name: "Guilford County", displayName: "Guilford County, North Carolina" },
  { id: "US-GA-GWINNETT-COUNTY", countryCode: "US", slug: "gwinnett-county-georgia", name: "Gwinnett County", displayName: "Gwinnett County, Georgia" },
  { id: "US-OH-HAMILTON-COUNTY", countryCode: "US", slug: "hamilton-county-ohio", name: "Hamilton County", displayName: "Hamilton County, Ohio" },
  { id: "US-TX-HARRIS-COUNTY", countryCode: "US", slug: "harris-county-texas", name: "Harris County", displayName: "Harris County, Texas" },
  { id: "US-TX-HAYS-COUNTY", countryCode: "US", slug: "hays-county-texas", name: "Hays County", displayName: "Hays County, Texas" },
  { id: "US-MN-HENNEPIN-COUNTY", countryCode: "US", slug: "hennepin-county-minnesota", name: "Hennepin County", displayName: "Hennepin County, Minnesota" },
  { id: "US-GA-HENRY-COUNTY", countryCode: "US", slug: "henry-county-georgia", name: "Henry County", displayName: "Henry County, Georgia" },
  { id: "US-IN-HENRY-COUNTY", countryCode: "US", slug: "henry-county-indiana", name: "Henry County", displayName: "Henry County, Indiana" },
  { id: "US-FL-HILLSBOROUGH-COUNTY", countryCode: "US", slug: "hillsborough-county-florida", name: "Hillsborough County", displayName: "Hillsborough County, Florida" },
  { id: "US-SC-HORRY-COUNTY", countryCode: "US", slug: "horry-county-south-carolina", name: "Horry County", displayName: "Horry County, South Carolina" },
  { id: "US-MD-HOWARD-COUNTY", countryCode: "US", slug: "howard-county-maryland", name: "Howard County", displayName: "Howard County, Maryland" },
  { id: "US-TX-HUNT-COUNTY", countryCode: "US", slug: "hunt-county-texas", name: "Hunt County", displayName: "Hunt County, Texas" },
  { id: "US-MO-JACKSON-COUNTY", countryCode: "US", slug: "jackson-county-missouri", name: "Jackson County", displayName: "Jackson County, Missouri" },
  { id: "US-MO-JEFFERSON-COUNTY", countryCode: "US", slug: "jefferson-county-missouri", name: "Jefferson County", displayName: "Jefferson County, Missouri" },
  { id: "US-LA-JEFFERSON-PARISH-COUNTY", countryCode: "US", slug: "jefferson-parish-louisiana", name: "Jefferson Parish", displayName: "Jefferson Parish, Louisiana" },
  { id: "US-KS-JOHNSON-COUNTY", countryCode: "US", slug: "johnson-county-kansas", name: "Johnson County", displayName: "Johnson County, Kansas" },
  { id: "US-NC-JOHNSTON-COUNTY", countryCode: "US", slug: "johnston-county-north-carolina", name: "Johnston County", displayName: "Johnston County, North Carolina" },
  { id: "US-IL-KANE-COUNTY", countryCode: "US", slug: "kane-county-illinois", name: "Kane County", displayName: "Kane County, Illinois" },
  { id: "US-TX-KAUFMAN-COUNTY", countryCode: "US", slug: "kaufman-county-texas", name: "Kaufman County", displayName: "Kaufman County, Texas" },
  { id: "US-IL-KENDALL-COUNTY", countryCode: "US", slug: "kendall-county-illinois", name: "Kendall County", displayName: "Kendall County, Illinois" },
  { id: "US-CA-KERN-COUNTY", countryCode: "US", slug: "kern-county-california", name: "Kern County", displayName: "Kern County, California" },
  { id: "US-WA-KING-COUNTY", countryCode: "US", slug: "king-county-washington", name: "King County", displayName: "King County, Washington" },
  { id: "US-IN-LAKE-COUNTY", countryCode: "US", slug: "lake-county-indiana", name: "Lake County", displayName: "Lake County, Indiana" },
  { id: "US-SC-LEXINGTON-COUNTY", countryCode: "US", slug: "lexington-county-south-carolina", name: "Lexington County", displayName: "Lexington County, South Carolina" },
  { id: "US-IL-MADISON-COUNTY", countryCode: "US", slug: "madison-county-illinois", name: "Madison County", displayName: "Madison County, Illinois" },
  { id: "US-AZ-MARICOPA-COUNTY", countryCode: "US", slug: "maricopa-county-arizona", name: "Maricopa County", displayName: "Maricopa County, Arizona" },
  { id: "US-CA-MARIN-COUNTY", countryCode: "US", slug: "marin-county-california", name: "Marin County", displayName: "Marin County, California" },
  { id: "US-IN-MARION-COUNTY", countryCode: "US", slug: "marion-county-indiana", name: "Marion County", displayName: "Marion County, Indiana" },
  { id: "US-HI-MAUI-COUNTY", countryCode: "US", slug: "maui-county-hawaii", name: "Maui County", displayName: "Maui County, Hawaii" },
  { id: "US-IL-MCHENRY-COUNTY", countryCode: "US", slug: "mchenry-county-illinois", name: "McHenry County", displayName: "McHenry County, Illinois" },
  { id: "US-NJ-MONMOUTH-COUNTY", countryCode: "US", slug: "monmouth-county-new-jersey", name: "Monmouth County", displayName: "Monmouth County, New Jersey" },
  { id: "US-OR-MARION-COUNTY", countryCode: "US", slug: "marion-county-oregon", name: "Marion County", displayName: "Marion County, Oregon" },
  { id: "US-OR-MULTNOMAH-COUNTY", countryCode: "US", slug: "multnomah-county-oregon", name: "Multnomah County", displayName: "Multnomah County, Oregon" },
  { id: "US-NY-NASSAU-COUNTY", countryCode: "US", slug: "nassau-county-new-york", name: "Nassau County", displayName: "Nassau County, New York" },
  { id: "US-TX-NUECES-COUNTY", countryCode: "US", slug: "nueces-county-texas", name: "Nueces County", displayName: "Nueces County, Texas" },



  // fler regioner läggs till här senare
];

// Helpers (används av dynamic routes)
export function getRegionBySlug(slug: string): Region | undefined {
  return regions.find((r) => r.slug === slug);
}

export function getRegionById(id: RegionId): Region | undefined {
  return regions.find((r) => r.id === id);
}
