// config/tools.ts
import type { RegionId } from "./regions";

export type ToolId =
  | "income-tax"
  | "sales-tax"
  | "paycheck"
  | "property-tax";

export type ToolDefinition = {
  id: ToolId;
  name: string;
  label: string;
  basePath: string;
  component:
    | "IncomeTaxTool"
    | "SalesTaxTool"
    | "PaycheckTool"
    | "PropertyTaxTool";
  dataKey:
    | "incomeTax"
    | "salesTax"
    | "paycheck"
    | "propertyTax";
  supportedRegionIds: RegionId[];
};

export const tools: ToolDefinition[] = [
  {
    id: "income-tax",
    name: "Income tax calculator",
    label: "Income tax",
    basePath: "/tools/income-tax",
    component: "IncomeTaxTool",
    dataKey: "incomeTax",
    supportedRegionIds: [
      "US-VA",
      "US-MI",
      "US-MN",
      "US-UT",
      "US-AL",
      "US-OK",
      "US-HI",
      "US-KS",
      "US-ID",
      "US-KY",
      "US-IA",
      "US-ME",
      "US-DE",
      "US-MS",
      "US-OH",
      "US-AR",
      "US-MT",
      "US-NE",
    ],
  },
  {
    id: "sales-tax",
    name: "Sales tax calculator",
    label: "Sales tax",
    basePath: "/tools/sales-tax",
    component: "SalesTaxTool",
    dataKey: "salesTax",
    supportedRegionIds: [
      "US-AL",
      "US-AR",
      "US-AZ",
      "US-CO",
      "US-CT",
      "US-FL",
      "US-GA",
      "US-HI",
      "US-ID",
      "US-IN",
      "US-KS",
      "US-LA",
      "US-MD",
      "US-MA",
      "US-MI",
      "US-MN",
      "US-MO",
      "US-NV",
      "US-NJ",
      "US-NY",
      "US-NC",
      "US-OH",
      "US-OR",
      "US-PA",
      "US-RI",
      "US-SC",
      "US-SD",
      "US-TN",
      "US-UT",
      "US-VA",
      "US-WA",
      "US-WI",
      "US-WY",
      "US-PR",
      "US-CA-ALAMEDA-COUNTY",
      "US-FL-BROWARD-COUNTY",
      "US-NV-CLARK-COUNTY",
      "US-NY-ERIE-COUNTY",
      "US-OH-FRANKLIN-COUNTY",
      "US-PA-FRANKLIN-COUNTY",
      "US-NY-FRANKLIN-COUNTY",
      "US-TX-FRANKLIN-COUNTY",
      "US-FL-POLK-COUNTY",
      "US-NY-SUFFOLK-COUNTY",
      "US-TX-AUSTIN-CITY",
      "US-MA-BOSTON-CITY",
      "US-TX-DALLAS-CITY",
      "US-TX-HOUSTON-CITY",
      "US-MN-MINNEAPOLIS-CITY",
      "US-NY-NEW-YORK-CITY",
      "US-CA-SAN-FRANCISCO-CITY",
      "US-CA-SAN-JOSE-CITY",
      "US-UT-SALT-LAKE-CITY",
      "US-DC",
      "US-VT",
      "US-ME",
      "US-NC-WAKE-COUNTY",
      "US-NC-MECKLENBURG-COUNTY",
      "US-AZ-PHOENIX-CITY",
      "US-CO-DENVER-CITY",
    ],
  },
  {
    id: "paycheck",
    name: "Paycheck calculator",
    label: "Paycheck",
    basePath: "/tools/paycheck",
    component: "PaycheckTool",
    dataKey: "paycheck",
    supportedRegionIds: [
      "US-TX",
      "US-FL",
      "US-IL",
      "US-GA",
      "US-CO",
      "US-TN",
      "US-VA",
      "US-NV",
      "US-UT",
      "US-WA",
      "US-MI",
      "US-IN",
      "US-KY",
      "US-LA",
      "US-MN",
      "US-NY",
      "US-AL",
      "US-MO",
      "US-AZ",
      "US-WI",
      "US-OH",
      "US-MD",
      "US-NJ",
      "US-IA",
      "US-AK",
      "US-NM",
      "US-WY",
      "US-MS",
      "US-SD",
      "US-CT",
      "US-VT",
      "US-ND",
      "US-WV",
      "US-DC",
      "US-RI",
      "US-CO-COLORADO-SPRINGS-CITY",
    ],
  },  
  {
    id: "property-tax",
    name: "Property tax calculator",
    label: "Property tax",
    basePath: "/tools/property-tax",
    component: "PropertyTaxTool",
    dataKey: "propertyTax",
    supportedRegionIds: [
      "US-CA-ALAMEDA-COUNTY",
      "US-AR",
      "US-KS",
      "US-KY",
      "US-MI",
      "US-SD",
      "US-VT",
      "US-VA",
      "US-WV",
      "US-WI",
      "US-WY",
      "US-SC-AIKEN-COUNTY",
      "US-PA-ALLEGHENY-COUNTY",
      "US-IN-ALLEN-COUNTY",
      "US-SC-ANDERSON-COUNTY",
      "US-MD-ANNE-ARUNDEL-COUNTY",
      "US-MN-ANOKA-COUNTY",
      "US-AL-BALDWIN-COUNTY",
      "US-MD-BALTIMORE-COUNTY",
      "US-TX-BELL-COUNTY",
      "US-SC-BERKELEY-COUNTY",
      "US-NM-BERNALILLO-COUNTY",
      "US-CO-BOULDER-COUNTY",
      "US-TX-BRAZORIA-COUNTY",
      "US-FL-BROWARD-COUNTY",
      "US-NC-BUNCOMBE-COUNTY",
      "US-ND-BURLEIGH-COUNTY",
      "US-MN-CARVER-COUNTY",
      "US-SC-CHARLESTON-COUNTY",
      "US-OR-CLACKAMAS-COUNTY",
      "US-FL-CLAY-COUNTY",
      "US-MN-CLAY-COUNTY",
      "US-MO-CLAY-COUNTY",
      "US-NC-CLAY-COUNTY",
      "US-GA-COBB-COUNTY",
      "US-FL-COLLIER-COUNTY",
      "US-TX-COLLIN-COUNTY",
      "US-TX-COMAL-COUNTY",
      "US-CA-CONTRA-COSTA-COUNTY",
      "US-IL-COOK-COUNTY",
      "US-OH-CUYAHOGA-COUNTY",
      "US-MN-DAKOTA-COUNTY",
      "US-TX-DALLAS-COUNTY",
      "US-WI-DANE-COUNTY",
      "US-UT-DAVIS-COUNTY",
      "US-TX-DENTON-COUNTY",
      "US-SC-DORCHESTER-COUNTY",
      "US-CO-DOUGLAS-COUNTY",
      "US-NE-DOUGLAS-COUNTY",
      "US-OR-DOUGLAS-COUNTY",
      "US-IL-DUPAGE-COUNTY",
      "US-NC-DURHAM-COUNTY",
      "US-CO-EL-PASO-COUNTY",
      "US-TX-EL-PASO-COUNTY",
      "US-TX-ELLIS-COUNTY",
      "US-NY-ERIE-COUNTY",
      "US-FL-ESCAMBIA-COUNTY",
      "US-AL-ETOWAH-COUNTY",
      "US-VA-FAIRFAX-COUNTY",
      "US-GA-FORSYTH-COUNTY",
      "US-MD-FREDERICK-COUNTY",
      "US-CA-FRESNO-COUNTY",
      "US-TX-GALVESTON-COUNTY",
      "US-NC-GASTON-COUNTY",
      "US-TX-GRAYSON-COUNTY",
      "US-OH-GREENE-COUNTY",
      "US-SC-GREENVILLE-COUNTY",
      "US-NC-GUILFORD-COUNTY",
      "US-GA-GWINNETT-COUNTY",
      "US-OH-HAMILTON-COUNTY",
      "US-TX-HARRIS-COUNTY",
      "US-TX-HAYS-COUNTY",
      "US-MN-HENNEPIN-COUNTY",
      "US-GA-HENRY-COUNTY",
      "US-IN-HENRY-COUNTY",
      "US-FL-HILLSBOROUGH-COUNTY",
      "US-SC-HORRY-COUNTY",
      "US-MD-HOWARD-COUNTY",
      "US-TX-HUNT-COUNTY",
      "US-MO-JACKSON-COUNTY",
      "US-MO-JEFFERSON-COUNTY",
      "US-LA-JEFFERSON-PARISH-COUNTY",
      "US-KS-JOHNSON-COUNTY",
      "US-NC-JOHNSTON-COUNTY",
      "US-IL-KANE-COUNTY",
      "US-TX-KAUFMAN-COUNTY",
      "US-IL-KENDALL-COUNTY",
      "US-CA-KERN-COUNTY",
      "US-WA-KING-COUNTY",
      "US-IN-LAKE-COUNTY",
      "US-SC-LEXINGTON-COUNTY",
      "US-IL-MADISON-COUNTY",
      "US-AZ-MARICOPA-COUNTY",
      "US-CA-MARIN-COUNTY",
      "US-IN-MARION-COUNTY",
      "US-HI-MAUI-COUNTY",
      "US-IL-MCHENRY-COUNTY",
      "US-NJ-MONMOUTH-COUNTY",
      "US-OR-MARION-COUNTY",
      "US-OR-MULTNOMAH-COUNTY",
      "US-NY-NASSAU-COUNTY",
      "US-TX-NUECES-COUNTY",
    ],
  }  
  
];

export function getToolById(id: ToolId): ToolDefinition | undefined {
  return tools.find((tool) => tool.id === id);
}
